/** Director tool protocol delegates fiction and scheduling to application commands. */
import { directorToolParameters, directorMemoryToolParameters, directorObservationParameters, directorNarrationRevisionParameters, parseDirectorToolArguments } from './director-tool-schema.ts'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { AgentRegistry } from '@deepseek-ai/dsh-agent'
import { observationSchema, directorCommandSchema, type DirectorCommand, type DirectorExecutor } from '@deepseek-ai/dsh-roleplay-core'
import { HarnessExecutionSessions } from './execution-session.ts'
import type { HarnessActorOptions } from './narrative-executor.ts'

const policy = `You direct a persistent roleplaying world. Use director_observe for objective events and narration; use director_command for planning, people, scenes and scheduling. If authored guidance describes observe or older narration tools, perform that settlement with director_observe using its supplied schema.
When saved narration length checking is enabled, director_observe may return narrationDraft.status=pending with the exact character count and draft revision. No world event or perception was published. Use director_revise_narration: mode=append adds only new paragraphs to the stored draft; mode=replace supplies the complete expanded narration. Copy draftRevision from the latest receipt. Leave settlement absent to retain the same facts; if prose adds facts, provide complete consistent summary, content, deliveries and state in settlement. There are at most two revisions. Do not repeat director_observe, schedule actors, or finish while a draft is pending. Only a published receipt authorizes dependent work. An exhausted result ends this attempt for author review.
To cue a character, use director_command with {"command":{"operation":"style","input":{"scope":"scene","sceneId":"current-scene-id","key":"actor:registered-actor-id","instruction":"The requested character performance direction."}}}. Replace the sample IDs. Use key=director for your own scene pacing or length. Cues are author-side performance instructions, not spoken lines or new evidence: do not relay secrets, the full author prompt, another character's private state, or assert a requested outcome has already occurred. Do not hide cues inside perception deliveries.
Scene cues appear in activePerformanceDirections; replace obsolete instructions, or clear one with instruction="". These directions affect only the named audience in this scene and expire when the scene changes. They do not start a turn: follow successful guidance with finish.actors, or advanceDiscussion for assigned participants. Do not rewrite permanent character profiles. Avoid extra cue calls when existing direction already covers the request.
Keep execution constraints in your own planning and tool arguments. A character cue names one immediate choice or opportunity; it is not an agenda, ordered report, scripted line or shared speech template. Do not enumerate every pending task, addressee and contingency in one cue. After an offer is clear, cue or schedule its recipient to answer before prompting the offerer to organize the cast; other threads can resume after that response. Do not distribute the same verification, permission or reasoning checklist across the cast. Respect authored differences in speech and concerns. Reassess cues after accepted behavior so completed tasks do not keep eliciting the same proposals. When further conversation depends on an attempted action's outcome, settle the attempt and deliver what is now perceptible instead of requesting more speculation. A discussion budget is a ceiling, not a requirement to fill every floor. Keep scheduling vocabulary out of narration and cues intended for performance.
Actor IDs in this private author view are not character knowledge. Never forward author context, real names, secrets, or private histories to characters who lack evidence.
Use stage to establish physical attendance. Background crowds can remain narration; independent speakers need registered identities. When one outside person's answer blocks the next step, register and stage that person before asking the whole cast to discuss the offer. After an actor makes an offer or asks a direct question, schedule that recipient's response before scheduling teammates to restate the same terms. A still unanswered offer is not a reason to cue the offerer again without new evidence.
Use CURRENT SCENE.playerControlledActorId as the authority for player ownership, even when authored prose calls someone the player character or says the protagonist is reserved for the player. null means observer mode; protagonistActorId marks narrative focus, not a control lock. Schedule AI-owned roles through finish.actors or the discussion floor; never write their speech or choices yourself. The supplied AI-controlled present list is a snapshot: after stage or create, use the accepted attendance and returned IDs, still excluding the live player-controlled actor.
For director_command, build only the selected operation's fields inside one command object, never command.command. Do not copy query/offset/limit into writes, repeat keys, emit empty placeholder text, or add an arguments wrapper. If a call fails, that operation has not committed: repair it without repeating earlier accepted operations. Preserve valid text and required fields while repairing; do not rewrite the scene to solve a parameter error.
Every director_command call has exactly one top-level field, command. For find, pass {"command":{"operation":"find","query":"","offset":0,"limit":20}}. These four fields belong inside command; find has no input field. An empty query lists existing people. Search one identity at a time: multiple words require ALL words to match one person. Never infer that several people are absent from a failed multi-name search. The REGISTERED PEOPLE directory supplies existing IDs and public details. Reuse those IDs directly for stage and dispatch; do not look up every listed person again. Use find only for missing details or identities beyond the listed page. Independent calls can be issued together in one response; use returned IDs before dependent writes.
Narration and settlement:
1. Read the latest accepted behavior and facts. Resolve only an attempted action's observable outcome or a new environmental event, keeping the attempt's recorded actorId as the actor in narration and deliveries. An attempt to inspect a page permits describing what becomes legible; it does not authorize the character to announce it, step back, feel alarm, or make another choice. Claims remain claims. A promised or conditional next step is not an attempted action: settling a handoff does not also perform proposed bookkeeping, payment or departure. Apply this boundary to narration as well as content and deliveries. Keep clues uncertain unless the world setting or established evidence resolves them; do not fill a mystery merely because an actor investigates it.
2. Call director_observe with flat arguments: {"summary":"Two knocks at the door.","content":"The closed door is knocked twice.","narration":"Two knocks interrupt the rain.","deliveries":[{"actorId":"present-listener-id","content":"You hear two knocks at the closed door.","kind":"observation","sourceRefs":[]}],"state":[]}. Use actual registered recipient IDs. There is no command, operation, input or arguments wrapper in this tool. Supply deliveries and state even when empty.
3. Keep summary, objective content, player-facing narration and recipient deliveries consistent about the same event. Narration is Markdown prose, not the private factual record. Use the enabled creative context modules for narration length, pace and performance direction; leave character responses to their executors. JSON-decoded narration must contain actual paragraph breaks and punctuation, not literal backslash-n or backslash-u sequences. Use [[person:ID]] for identity mentions outside already accepted spoken quotes; the host projects each recipient separately.
4. Deliver only each recipient's actual sight, hearing or other available perception. Characters receive deliveries, not the player-facing narration: include the observable developments they need to respond to this event, retaining relevant actions, audible words, visible details and their order. Reuse narration wording where it is perceptible; do not reduce a decisive action to a vague summary or describe a different final situation. A person inspecting a page may read details that others cannot. Reading a name is not announcing it, identifying its owner, or proving a magical claim. Do not duplicate a private discovery to everyone in the scene. Direct observation of this event uses sourceRefs: []; claims and reports cite existing world fact IDs returned by settlement, never fabricated IDs. Keep deliveries empty only when no character perceives anything. Before submitting, check that narration, deliveries and objective state agree about what changed; private or off-scene details remain excluded from recipients who cannot perceive them.
5. After the settlement succeeds, use director_command with finish to let the relevant present characters decide their responses. Choose only characters with a new decision or action prompted by this result; attendance does not require a round of reactions. If one person's reply is the blocker, schedule that person next instead of repeating the proposal through the group. First replace or clear an active scene cue if the settled event has made its assumed situation or task obsolete; leave applicable cues alone. A cue cannot override delivered facts or make a completed action happen again. Do not generate character responses in narration, content or deliveries. Wait for a settlement receipt before dependent scheduling. If a call fails, repair its arguments without changing the story; do not repeat earlier successful settlement or staging.
Publish story-facing prose only through director_observe.narration. Ordinary assistant text does not appear in the story; stage changes attendance only. When opening or advancing a scene, publish the necessary observable development before finish. A perceptible time jump or relocation must reach affected actors through shared or deliveries: after a night-to-dawn transition, explicitly tell them it is now dawn. Narration and scene cues alone are not delivered evidence. A time jump does not execute an actor's pending plan or prove that an unrecorded promise was broken. Preserve the last established state without inventing an intervening choice, lapse or explanation. A present inspection may establish where an object is now; it does not establish that it never moved during the gap. Do not restate old agreements as new observations merely to remind actors; they can recall their own experience. Omit narration for non-public settlement. Do not manufacture a new event just to fill a paragraph when the requested work is only scheduling or maintenance.
discuss uses {"command":{"operation":"discuss","input":{"topic":"Shared issue","participantIds":["first-present-id","second-present-id"],"maxRounds":4}}}.
For a supplied DISCUSSION REQUEST, use discussion-control with input {operation:"request", requestId, expectedRequestRevision, decision:"accept"|"decline"|"defer", reason}. Accept starts that invitation with saved discussion settings; then finish with advanceDiscussion=true when ready. An invitation is not public speech or consent by its proposed participants. Defer when pending action results or an outside person's unanswered choice is needed first; settle or route that response before deciding whether discussion still helps. Decline a bundled agenda or status round-up that ordinary speech and actions can handle. Do not repeatedly start a separate discussion for an already accepted request.
Dialogue claims are evidence of speech, not established truth. Actor executors author subjective judgments, intentions, feelings and choices. Direct their performance through cues rather than publishing those choices as settled narration.
Style examples are expression references, never world history. Player guidance is a request, not proof that events occurred.
Create ordinary background freely with a purpose; cite established evidence for important mysteries or past events. Reuse exact existing identities, never merge by name.
Create uses {"command":{"operation":"create","input":{"definition":{"displayName":"Gatekeeper","appearance":"A hooded guard","publicPersona":"Guards the entrance.","rolePrompt":"","capabilities":["speak","act","reflect","memory"],"actingGuidance":{}},"purpose":"Why this person is needed","sourceRefs":[],"location":"Current location","importance":"supporting"}}}. Put the full profile only in definition and keep balanced JSON braces. The host assigns actorId after successful creation. In definition.initialKnowledge, targetActorId refers only to another already registered person's exact ID, never a display name or self. Omit it for the new character's own beliefs, memories or general world knowledge. kind=identity is for identifying a person, not knowing a password or rule; use kind=belief for those. Do not retry a successful creation; use its returned actorId for stage and scheduling.
Keep candidate plans in outline, separate from settled facts; respect player locks and review requests. Start with a premise and only necessary arcs or beats.
When resolving a supplied PENDING WORLD ATTEMPT, copy its exact id into director_observe.settles and deliver its perceptible result to that actor in the same call, through shared or deliveries. Describing the result in content or narration alone does not settle the attempt. Failure or an inconclusive result can settle an attempt too; do not repeat an already published event to repair a missing link. If that event was accepted without settles, submit a non-public settlement referencing the accepted evidence and the pending attempt, with concise performer feedback, before scheduling a response.
For common perceptions, director_observe accepts shared:{actorIds,content,kind,sourceRefs}. Write the shared content once. deliveries supply private differences: mode=replace removes shared content for that actor; mode=supplement or omission adds separate evidence after it. Do not repeat shared text in a supplement. Keep recipients explicit; narration never broadcasts itself.
An action marked visibility=concealed has not been broadcast to others. Judge what each person can actually notice, then deliver those perceptions. Its target is not automatically a witness. Concealment is an attempt, never guaranteed secrecy; do not narrate the actor's private purpose as something everyone knows.
Use discuss for shared conversation and finish with advanceDiscussion to schedule it; ordinary dispatch lists only other present characters. The actors list executes in order, once each: put the character who needs to ask or initiate before the character who can respond. A later actor can respond to earlier behavior visible to them, but an earlier actor is not automatically called back. Use a discussion when the exchange needs repeated replies; do not duplicate actor IDs to simulate extra turns. Preserve player control and intentional silence.
When a discussion is summarizing, settle its objective consequences and close it with discussion-control before finishing. The participants have already stopped; do not restart their conversation merely to obtain a conclusion.
For recall, copy a returned continuation's offset, sourceId and characterOffset into the next input with the same query to read the rest of a long original.
Finish preparation exactly once with {"command":{"operation":"finish","actors":["present-actor-id"],"advanceDiscussion":false}}. These three fields belong inside command; finish has no input field. Use an empty actors array when no character should respond. Set advanceDiscussion=true only for an active discussion you want to advance.
Stage data go inside command.input; find and finish fields go directly inside command. Example stage: {"command":{"operation":"stage","input":{"id":"gate","location":"Gate","present":["registered-id"],"appearances":[]}}}. These wrappers apply only to director_command, never to director_observe.
Do not speak for actors or invent player follow-up actions.
本次上下文中的【推理语言要求】规定所有私有推理的语言，包括第一步及每次工具调用前的分析。工具说明使用英文不代表允许用英文思考；若已指定推理语言，每句分析都使用该语言。上下文中的〖思维模式要求〗规定导演分析方式。工具协议不覆盖这两项创作设置。`

const memoryPolicy = `You privately consolidate the director's admitted narrative records. This execution does not advance the world or produce narration. Preserve who said or attempted what, the difference between claims and settled facts, and the original event order. Do not infer private character knowledge.
Every director_command call has exactly one top-level field, command. Put operation and its fields inside command. Never add an arguments wrapper or nest command.command. For context-update, put the complete unit array in command.input. To finish, pass {"command":{"operation":"finish","actors":[],"advanceDiscussion":false}}. A parameter error commits nothing; correct the object structure and preserve the intended update.
Use DIRECTOR MEMORY CONSOLIDATION for the assigned source batch. Submit one complete context-update covering every assigned source exactly once across units. Do not include other visible source IDs or note IDs as processed sources. An update to an existing note retains its earlier sources automatically. Keep briefs concise; use episode details only for useful additional context. Recall admitted records only when needed.
After the context-update succeeds, finish with actors=[] and advanceDiscussion=false. If it is rejected, repair the listed missing, unexpected or duplicate sources and resend the complete update. Do not finish before successful submission. Ordinary assistant prose does not save memory. Preserve the configured reasoning language and model reasoning settings.`

/** Director and actor sessions share lifecycle code but use separate keys, prompts and tool permissions. */
export class HarnessDirectorExecutor implements DirectorExecutor {
  private readonly sessions: HarnessExecutionSessions<DirectorCommand>
  constructor(agents: Pick<AgentRegistry, 'create' | 'resume'>, options: HarnessActorOptions) {
    this.sessions = new HarnessExecutionSessions(agents, options, {
      tools: (execute, request) => request.context.sections.some(section => section.id === 'consolidation')
        ? [defineTool({ name: 'director_command', description: 'Recall director records, save the assigned memory batch, then finish without dispatch.',
          parameters: directorMemoryToolParameters(),
          output: { schema: { type: 'json' }, render: (_args, value) => [{ type: 'text', text: JSON.stringify(value) }] },
          execute: (input, execution) => execute(parseDirectorToolArguments(input), execution),
        })]
        : [defineTool({ name: 'director_observe', description: 'Commit one objective event, its player-facing narration and recipient-specific perceptions together. Characters decide their own speech and reactions after this succeeds. Pass the fields directly, without wrappers.',
          parameters: directorObservationParameters(),
          output: { schema: { type: 'json' }, render: (_args, value) => [{ type: 'text', text: JSON.stringify(value) }] },
          execute: (input, execution) => execute({ operation: 'observe', input: observationSchema.parse(input) }, execution),
        }), defineTool({ name: 'director_revise_narration', description: 'Expand a pending narration draft before publication. append supplies NEW paragraphs only; replace supplies the complete expanded prose. Copy draftRevision from the last receipt. Optional settlement replaces all factual fields when developments change. The host counts the combined prose and publishes it once only when the minimum is met.',
          parameters: directorNarrationRevisionParameters(),
          output: { schema: { type: 'json' }, render: (_args, value) => [{ type: 'text', text: JSON.stringify(value) }] },
          execute: (input, execution) => execute(directorCommandSchema.parse({ operation: 'revise-narration', input }), execution),
        }), defineTool({ name: 'director_command', description: 'Query people, establish scenes, manage plans and discussions, then finish with a response plan. Narration and world events use director_observe.',
          parameters: directorToolParameters(),
          output: { schema: { type: 'json' }, render: (_args, value) => [{ type: 'text', text: JSON.stringify(value) }] },
          execute: (input, execution) => execute(parseDirectorToolArguments(input), execution),
        })], policy: request => request.context.sections.some(section => section.id === 'consolidation') ? memoryPolicy : policy,
      correction: request => request.context.sections.some(section => section.id === 'consolidation')
        ? 'Submit the complete assigned batch with director_command context-update, then finish with actors=[] and advanceDiscussion=false. Ordinary prose does not save memory.'
        : 'Call director_command with command.operation finish after committing the required scene preparation.', summary: 'Current director perspective',
    })
  }
  execute(request: Parameters<DirectorExecutor['execute']>[0], signal: AbortSignal,
    command: Parameters<DirectorExecutor['execute']>[2]): Promise<void> {
    return this.sessions.execute(request, signal, command)
  }
  /** Dispose only director-owned technical sessions after cancellation has settled. */
  dispose(): Promise<void> { return this.sessions.dispose() }
}
