/** Keyless browser acceptance runs the independent product without legacy Story writers. */
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from 'playwright'
import { expect, it } from 'vitest'
import type {} from '@deepseek-ai/dsh-roleplay-services'
import type { BookId, CommandId } from '@deepseek-ai/dsh-roleplay-core/types'
import { launchWebScaffold, watchConsole } from './scaffold.ts'
import { newEnglishPage } from './support.ts'
import { MockAdapter, toolCallResponse } from '../../../packages/core/agent-loop/tests/mock-adapter.ts'
import { ReasoningEffortId, type GenerateOptions } from '@deepseek-ai/dsh-llm'

class RecordedMock extends MockAdapter {
  override async listModels(provider: string) {
    return [{ provider, id: 'mock', name: 'Mock' }, { provider, id: 'mock-next', name: 'Mock Next' }]
  }
  override async resolveModel(provider: string, model: string) {
    return { ...await super.resolveModel(provider, model), ...(model === 'mock-next' ? { reasoning: {
      efforts: [{ id: ReasoningEffortId('low'), name: 'Low' }, { id: ReasoningEffortId('high'), name: 'High' }],
      defaultEffort: ReasoningEffortId('low'),
    } } : {}) }
  }
  override reconstructRequest(options: GenerateOptions): string { return JSON.stringify(options) }
}

it('plays an independent instance with player name annotations and consistent author review cards', async () => {
  const root = await mkdtemp(join(tmpdir(), 'storyweaver-independent-browser-'))
  const scaffold = await launchWebScaffold({
    extraOverlayPath: fileURLToPath(new URL('../../../packages/experimental/roleplay-web-profile/cordis.patch.yml', import.meta.url)),
    extraInstallAnchors: [fileURLToPath(new URL('../../../packages/experimental/roleplay-web-profile/package.json', import.meta.url))],
    directoryPickerMode: 'overlay', extraEntryOverrides: [
      { id: 'story-home', config: { root } },
      { id: 'roleplay-services', config: { databasePath: join(root, 'narrative.sqlite'), provider: 'mock', model: 'mock',
        journalMode: 'wal', busyTimeoutMs: 1000, queryPageLimit: 40, directorCommandLimit: 12,
        discussionTurnLimit: 16, maxContextUpdateUnits: 16, notificationIntervalMs: 10,
        recallCharacterLimit: 6000,
        characterLimits: { maxCoreMemories: 64, maxRecallResults: 8, maxTextBytes: 16384, maxSourceRefs: 16,
          maxActiveGoals: 32, maxScheduledIntentions: 32 },
      } },
    ],
  })
  const browser = await chromium.launch()
  try {
    expect(scaffold.ctx.get('storyRegistry')).toBeUndefined()
    expect(scaffold.ctx.get('actor')).toBeUndefined()
    const draft = scaffold.ctx.roleplayBooks.saveDraft({ id: 'ledger' as BookId, expectedRevision: 0, title: 'Independent Ledger', resources: [],
      document: { schemaVersion: 6, id: 'ledger', title: 'Independent Ledger', directorPrompt: '', directorGuidance: {},
        characters: [{ actorId: 'keeper', displayName: 'UNREVEALED NAME', appearance: 'A flour-dusted innkeeper',
          initialKnowledge: [{ text: 'The inn is a safe meeting place.', kind: 'belief', attitude: 'doubted' },
            ...Array.from({ length: 12 }, (_, index) => ({ text: `Remembered guest ${index + 1}.`, kind: 'belief', attitude: 'believed' }))],
          rolePrompt: '', publicPersona: 'Keeps an inn', capabilities: ['speak', 'act', 'reflect'], actingGuidance: {} }] } })
    const version = scaffold.ctx.roleplayBooks.publish(draft.id, draft.revision)
    const instance = scaffold.ctx.roleplayInstances.createStory({ templateVersionId: version.id, commandId: 'create-A' as CommandId }).instance
    const page = await newEnglishPage(browser)
    await page.addInitScript(() => { localStorage.setItem('dsh.conversation.contentWidth', '840') })
    const console = watchConsole(page)
    await page.goto(scaffold.authenticatedUrl, { waitUntil: 'load' })
    try { await page.getByRole('complementary', { name: 'Books and independent stories' })
      .getByRole('button', { name: /Story run \d+ Pinned version 1/u }).click({ timeout: 30000 }) }
    catch (error) { throw new Error(`${await page.locator('body').innerText()}\n${JSON.stringify(console.pageErrors)}`, { cause: error }) }
    await page.getByRole('heading', { name: 'Independent Ledger', exact: true }).waitFor()
    const openingControl = page.getByRole('combobox', { name: 'Player control', exact: true })
    await expect.poll(() => openingControl.locator('option[value="keeper"]').textContent()).toContain('Off scene')
    await openingControl.selectOption('keeper')
    await expect.poll(() => openingControl.inputValue()).toBe('keeper')
    await page.getByText(/This character is off scene; your control is retained/u).waitFor()
    await page.getByRole('textbox', { name: 'What you say', exact: true }).fill('Hello before the scene.')
    expect(await page.getByRole('button', { name: 'Submit', exact: true }).isDisabled()).toBe(true)
    await page.getByRole('textbox', { name: 'What you say', exact: true }).fill('')
    await openingControl.selectOption('')
    await expect.poll(() => openingControl.isEnabled()).toBe(true)
    scaffold.ctx.roleplayPeople.stage({ instanceId: instance.id, id: 'stage' as CommandId,
      expectedRevision: scaffold.ctx.roleplayHistory.snapshot(instance.id).instance.revision, principal: { kind: 'player' } },
    { id: 'inn', location: 'Quiet inn', present: ['keeper'], appearances: [] })
    await expect.poll(() => openingControl.locator('option[value="keeper"]').textContent()).not.toContain('Off scene')
    await page.getByRole('button', { name: 'Create new story', exact: true }).last().click()
    await page.getByRole('button', { name: 'Import your work', exact: true }).last().waitFor()
    await expect((await page.getByRole('region', { name: 'Storybooks', exact: true }).ariaSnapshot())
      .replaceAll(instance.id.slice(-6), '<instance>') + '\n').toMatchFileSnapshot('./expected/narrative-library.aria.txt')
    expect(scaffold.ctx.roleplayBooks.instances()).toHaveLength(1)
    await page.getByLabel('Search stories', { exact: true }).fill('No matching story')
    expect(await page.getByRole('button', { name: /Story run \d+ Pinned version 1/u }).count()).toBe(0)
    await page.getByLabel('Search stories', { exact: true }).fill('Ledger')
    await page.getByRole('button', { name: /Story run \d+ Pinned version 1/u }).click()
    await page.getByLabel('Search stories', { exact: true }).fill('')
    expect(await page.getByRole('button', { name: 'Interrupt and pause', exact: true }).count()).toBe(0)
    await page.getByRole('combobox', { name: 'Player control', exact: true }).selectOption('keeper')
    await expect.poll(() => page.getByRole('combobox', { name: 'Player control', exact: true }).inputValue()).toBe('keeper')
    await page.reload({ waitUntil: 'load' })
    await expect.poll(() => page.getByRole('combobox', { name: 'Player control', exact: true }).inputValue()).toBe('keeper')
    await expect.poll(() => page.getByRole('combobox', { name: 'Select character', exact: true }).inputValue()).toBe('keeper')
    await page.getByRole('combobox', { name: 'Player control', exact: true }).selectOption('')
    await expect.poll(() => page.getByRole('combobox', { name: 'Player control', exact: true }).inputValue()).toBe('')
    expect(await page.getByRole('navigation', { name: 'Story run tools', exact: true }).count()).toBeLessThanOrEqual(1)
    await page.getByRole('button', { name: 'People in this scene', exact: true }).click()
    await expect.poll(() => page.getByRole('dialog', { name: 'People in this scene', exact: true }).textContent()).toContain('UNREVEALED NAME')
    await page.getByRole('button', { name: 'View knowledge', exact: true }).click()
    const personDialog = page.getByRole('dialog', { name: 'Characters', exact: true })
    await personDialog.getByText('The inn is a safe meeting place.', { exact: true }).first().waitFor()
    const personBox = await personDialog.boundingBox()
    expect(personBox?.y).toBeGreaterThanOrEqual(0)
    expect((personBox?.y ?? 0) + (personBox?.height ?? 0)).toBeLessThanOrEqual(page.viewportSize()!.height)
    await page.keyboard.press('Escape')
    await personDialog.waitFor({ state: 'hidden' })
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/ui-recovery-opening.png', import.meta.url)), fullPage: true })
    await page.getByRole('button', { name: 'Observe and advance', exact: true }).click()
    await page.getByRole('textbox', { name: 'Player action or direction' }).fill('The shutters rattle in the wind.')
    await page.getByRole('button', { name: 'Director guidance', exact: true }).click()
    expect(await page.getByRole('textbox', { name: 'Player action or direction' }).inputValue()).toBe('The shutters rattle in the wind.')
    await page.getByRole('button', { name: 'World intervention', exact: true }).click()
    await page.getByRole('button', { name: 'Submit', exact: true }).click()
    await page.locator('article').getByText('The shutters rattle in the wind.', { exact: true }).waitFor()
    await expect.poll(() => page.getByRole('textbox', { name: 'Player action or direction' }).inputValue()).toBe('')
    const sendAdapter = new RecordedMock(['hang', toolCallResponse('finish-retry', 'director_command', { command: {
      operation: 'finish', actors: [], advanceDiscussion: false,
    } })])
    const removeSendAdapter = scaffold.ctx.effect(() => scaffold.ctx.llm.registerAdapter(['mock'], sendAdapter))
    await page.getByRole('button', { name: 'Observe and advance', exact: true }).click()
    const composer = page.getByRole('textbox', { name: 'Player action or direction' })
    await composer.fill('Watch the door.')
    await composer.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
    expect(sendAdapter.requests).toHaveLength(0)
    await composer.press('Shift+Enter')
    expect(await composer.inputValue()).toBe('Watch the door.\n')
    expect(sendAdapter.requests).toHaveLength(0)
    await composer.press('Enter')
    await page.getByText('Request in progress', { exact: true }).waitFor()
    await page.locator('article').getByText('Watch the door.', { exact: true }).waitFor()
    await expect.poll(() => sendAdapter.requests.length).toBe(1)
    expect(await page.getByRole('button', { name: 'Running…', exact: true }).isDisabled()).toBe(true)
    await page.getByRole('button', { name: 'Interrupt and pause', exact: true }).click()
    await page.getByText('Not completed; your text is preserved', { exact: true }).waitFor()
    expect(await composer.inputValue()).toBe('Watch the door.\n')
    await composer.press('Enter')
    await expect.poll(() => composer.inputValue()).toBe('')
    expect(sendAdapter.requests).toHaveLength(2)
    await removeSendAdapter()
    await page.getByRole('button', { name: 'Embody character', exact: true }).click()
    await page.getByLabel('Select character', { exact: true }).selectOption('keeper')
    await expect.poll(() => page.getByRole('main').textContent()).toContain('UNREVEALED NAME')
    await page.getByRole('button', { name: 'Author workspace', exact: true }).click()
    await page.getByLabel('Characters', { exact: true }).selectOption('keeper')
    await page.getByLabel('Director guidance', { exact: true }).fill('A restrained narrator')
    scaffold.ctx.roleplayConfiguration.setSettings({ instanceId: instance.id, id: 'external-setting' as CommandId,
      expectedRevision: scaffold.ctx.roleplayHistory.snapshot(instance.id).instance.revision, principal: { kind: 'player' } },
    { overrides: { premise: 'The letter arrives before midnight.' }, reason: 'Concurrent author edit' })
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await page.getByText(/roleplay-conflict:/u).waitFor()
    expect(await page.getByLabel('Director guidance', { exact: true }).inputValue()).toBe('A restrained narrator')
    await page.getByRole('main').getByRole('button', { name: 'Refresh', exact: true }).click()
    expect(await page.getByLabel('Director guidance', { exact: true }).inputValue()).toBe('A restrained narrator')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).settings.effective.directorPrompt).toBe('A restrained narrator')
    expect(scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).settings.effective.premise).toBe('The letter arrives before midnight.')
    await page.getByText('Director outline and proposals', { exact: true }).click()
    const planning = page.getByText('Director outline and proposals', { exact: true }).locator('..')
    await planning.getByLabel('Director update policy', { exact: true }).selectOption('review_all')
    await planning.getByLabel('Outline premise', { exact: true }).fill('A letter offers a choice, not an answer.')
    await planning.getByLabel('Lock premise against director changes', { exact: true }).check()
    await planning.getByLabel('Reason for change', { exact: true }).fill('Preserve player choices')
    await planning.getByRole('button', { name: 'Save outline', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).outline.updateMode).toBe('review_all')
    const plan = scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id })
    scaffold.ctx.roleplayPlanning.patch({ instanceId: instance.id, id: 'outline-proposal' as CommandId,
      expectedRevision: plan.instance.revision, principal: { kind: 'director', attempt: 'outline-proposal', epoch: plan.instance.epoch } },
    { expectedRevision: plan.outline.revision, reason: 'The letter may have several owners',
      themes: [{ id: 'ownership', text: 'Who owns a memory?' }] })
    await planning.getByRole('button', { name: 'Refresh outline and revision', exact: true }).click()
    await planning.getByText('The letter may have several owners', { exact: true }).waitFor()
    await planning.getByRole('button', { name: 'Approve', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).outline.themes[0]?.text).toBe('Who owns a memory?')
    expect(scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).outline.premiseLocked).toBe(true)
    await page.getByRole('button', { name: 'Performance style', exact: true }).click()
    const speechStyle = page.getByLabel('Speech style', { exact: true })
    await speechStyle.fill('')
    await speechStyle.pressSequentially('Quiet words')
    expect(await speechStyle.inputValue()).toBe('Quiet words')
    await page.getByLabel('Performance examples (not lived history)', { exact: true }).fill('First line\n\nSecond line')
    await page.getByText('Personal style presets', { exact: true }).click()
    await page.getByLabel('Preset name', { exact: true }).fill('Browser copy')
    await page.getByRole('button', { name: 'Save personal preset', exact: true }).click()
    await page.getByRole('button', { name: 'Natural speech', exact: true }).click()
    await page.getByRole('button', { name: 'Browser copy', exact: true }).click()
    expect(await speechStyle.inputValue()).toBe('Quiet words')
    await page.getByRole('button', { name: 'Save', exact: true }).first().click()
    await expect.poll(() => { const profile = scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id, actorId: 'keeper' }).actor?.profile
      return profile?.kind === 'actor' ? profile.guidance.speechStyle : ''
    }).toBe('Quiet words')
    await page.getByRole('button', { name: 'Context', exact: true }).click()
    await page.getByText('Narrative messages from the saved recipe', { exact: true }).waitFor()
    expect(await page.getByRole('heading', { name: 'Context recipe', exact: true }).count()).toBe(1)
    const recipeForm = page.getByRole('heading', { name: 'Context recipe', exact: true }).locator('..')
    const policyCard = recipeForm.locator('details').filter({ has: page.locator('summary').filter({ hasText: 'Behavior rules' }) })
    await policyCard.locator('summary').click()
    await policyCard.getByRole('checkbox', { name: 'Enabled', exact: true }).uncheck()
    await policyCard.getByRole('button', { name: 'Move down', exact: true }).click()
    await recipeForm.getByRole('button', { name: 'Optimize actor cache order', exact: true }).click()
    expect(await recipeForm.locator('summary').first().textContent()).toContain('Behavior rules')
    await recipeForm.getByRole('button', { name: 'Add reference module', exact: true }).click()
    await recipeForm.getByRole('group').last().getByLabel('Module title', { exact: true }).fill('Browser reference')
    await recipeForm.getByRole('group').last().getByLabel('Reference text (not lived history or facts)', { exact: true }).fill('Preserve the letter mystery.')
    await page.reload()
    await expect.poll(() => page.getByLabel('Characters', { exact: true }).inputValue()).toBe('keeper')
    await policyCard.locator('summary').click()
    expect(await policyCard.getByRole('checkbox', { name: 'Enabled', exact: true }).isChecked()).toBe(false)
    expect(await recipeForm.getByRole('group').last().getByLabel('Module title', { exact: true }).inputValue()).toBe('Browser reference')
    await recipeForm.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).contextRecipe.actor.find(item => item.id === 'policy')?.enabled).toBe(false)
    const savedRecipe = scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).contextRecipe
    const actorOrder = savedRecipe.actor.map(item => item.id)
    expect(actorOrder.indexOf('knowledge')).toBeLessThan(actorOrder.indexOf('people'))
    expect(actorOrder.indexOf('lifecycle')).toBeLessThan(actorOrder.indexOf('evidence'))
    expect(savedRecipe.actor.at(-1)).toMatchObject({ title: 'Browser reference', content: 'Preserve the letter mystery.' })
    await recipeForm.locator('summary').filter({ hasText: 'Tool guidance' }).click()
    await recipeForm.getByRole('button', { name: 'Tool guidance', exact: true }).click()
    const sourceEditor = page.getByRole('dialog', { name: 'Edit context source', exact: true })
    await sourceEditor.getByRole('textbox', { name: 'Tool guidance', exact: true }).fill('Use tools to record accepted actions; preserve private knowledge.')
    await sourceEditor.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).settings.effective.contextRules.actor.tools).toContain('preserve private knowledge')
    await sourceEditor.getByRole('button', { name: 'Close panel', exact: true }).click()

    await page.getByRole('button', { name: 'Characters', exact: true }).click()
    const cognition = page.getByRole('heading', { name: 'Knowledge, sources and history', exact: true }).locator('..')
    await cognition.getByText('The inn is a safe meeting place.', { exact: true }).first().waitFor()
    expect(await cognition.getByText('Doubted', { exact: true }).first().isVisible()).toBe(true)
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/player-ui-cognition.png', import.meta.url)), fullPage: true })
    await page.getByRole('button', { name: 'Create supporting character', exact: true }).click()
    for (const [label, text] of [['True name (author information)', 'New messenger'],
      ['Appearance and first encounter label', 'A traveler carrying a sealed letter'],
      ['Personality and habits', 'Chooses words carefully'], ['Narrative purpose and basis', 'Brings a letter to the inn']]) {
      await page.getByLabel(label!, { exact: true }).fill(text!)
    }
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayViews.authorPeople(instance.id, { query: '', offset: 0, limit: 20 }).total).toBe(2)
    await page.getByLabel('Narrative purpose and basis', { exact: true }).waitFor({ state: 'detached' })
    await page.getByLabel('Characters', { exact: true }).selectOption('keeper')
    await page.getByRole('button', { name: 'State system', exact: true }).click()
    const subjective = page.getByRole('heading', { name: 'Subjective character state', exact: true }).locator('..')
    await subjective.getByRole('button', { name: 'Add state field' }).click()
    for (const [label, text] of [['Field name', 'Unease'], ['Description', 'An uneasy feeling about the letter'],
      ['Group', 'Mind'], ['Current value', 'Wary'], ['Reason for change', 'Player correction']]) await subjective.getByLabel(label!, { exact: true }).fill(text!)
    await subjective.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayViews.authorCognition(instance.id, 'keeper').current.dynamicState.entries.length).toBe(1)
    await page.getByRole('button', { name: 'Characters', exact: true }).click()
    await page.getByText('Scene and attendance', { exact: true }).click()
    await page.getByText('Scene and attendance', { exact: true }).locator('..').getByLabel('New messenger', { exact: true }).check()
    await page.getByRole('button', { name: 'Save scene and attendance', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id }).scene.present.length).toBe(2)
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    await page.getByRole('button', { name: 'People in this scene', exact: true }).click()
    await expect.poll(() => page.getByRole('dialog', { name: 'People in this scene', exact: true }).textContent()).toContain('UNREVEALED NAME')
    await page.getByRole('dialog', { name: 'People in this scene', exact: true }).getByRole('button', { name: 'Close panel', exact: true }).click()
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    await page.getByRole('button', { name: 'Observe and advance', exact: true }).click()
    await page.locator('article').getByText('The shutters rattle in the wind.', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'More actions', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Group discussion', exact: true }).click()
    await page.getByLabel('Discussion topic', { exact: true }).fill('What should we do with the letter?')
    await page.getByLabel(/A flour-dusted innkeeper.*（UNREVEALED NAME）/u).check()
    await page.getByLabel(/A traveler carrying a sealed letter.*（New messenger）/u).check()
    await page.getByLabel('Maximum rounds', { exact: true }).fill('1')
    await page.getByRole('button', { name: 'Create discussion', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Close panel', exact: true }).click()
    const preparation = page.getByRole('region', { name: 'Group discussion preparation', exact: true })
    await preparation.waitFor()
    await expect.poll(() => preparation.textContent()).toContain('Waiting to prepare · 0/2 ready')
    await preparation.scrollIntoViewIfNeeded()
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/discussion-preparation.png', import.meta.url)) })
    await page.getByRole('button', { name: 'Discussion controls', exact: true }).click()
    await page.getByRole('button', { name: 'Interrupt and wait for player', exact: true }).click()
    await page.getByRole('button', { name: 'Resume discussion', exact: true }).click()
    const discussionId = scaffold.ctx.roleplayPlay.read({ instanceId: instance.id, audience: { kind: 'observer' }, offset: 0, limit: 1 }).discussion!.id
    const prepareCharacter = (options: GenerateOptions) => {
      const request = scaffold.ctx.sessions.get(options.sessionId!)!.events.findLast(event => event.type === 'roleplay/execution-request')!
      if (request.type !== 'roleplay/execution-request') throw new Error('Missing preparation context')
      const keeper = 'actorId' in request.data.context && request.data.context.actorId === 'keeper'
      return toolCallResponse(keeper ? 'prepare-one' : 'prepare-two', 'npc_commit_turn', { posture: 'watching',
        ...(keeper ? { thoughts: [{ content: 'I should ask before opening the letter.' }] } : {}),
        discussion: { action: 'pass', eagerness: keeper ? 'high' : 'low', stance: keeper ? 'Respect the messenger.' : 'Watch the seal.' } })
    }
    const storyAdapter = new RecordedMock([
      prepareCharacter, prepareCharacter,
      toolCallResponse('speak-one', 'npc_commit_turn', { posture: 'finished', discussion: { action: 'speak', eagerness: 'high' },
        behavior: [{ kind: 'speech', text: 'Let us examine the letter.' }],
        context_update: [{ sourceIds: ['$behavior:0'], disposition: 'represented', reason: 'Keep the proposal and its source.',
          changes: [{ operation: 'add', kind: 'claim', text: 'I proposed examining the letter.', sourceIds: ['$behavior:0'],
            episode: { topic: 'The unopened letter', experience: 'I asked to examine the letter.',
              interpretation: 'It may contain a clue.', impact: 'I want to examine it.', unresolved: [] } }] }] }),
      toolCallResponse('speak-two', 'npc_commit_turn', { posture: 'finished', discussion: { action: 'speak', eagerness: 'low' },
        behavior: [{ kind: 'speech', text: 'First, check the seal.' }] }),
      toolCallResponse('close-discussion', 'director_command', { command: { operation: 'discussion-control',
        input: { operation: 'close', discussionId, status: 'completed' } } }),
      toolCallResponse('finish-discussion', 'director_command', { command: { operation: 'finish', actors: [], advanceDiscussion: false } }),
      { hangAfter: [
        { type: 'reasoning-delta', index: 0, text: 'A private live hypothesis.' },
        { type: 'text-delta', index: 1, text: 'A private diagnostic draft.' },
      ] },
    ])
    scaffold.ctx.effect(() => scaffold.ctx.llm.registerAdapter(['mock'], storyAdapter))
    await page.getByRole('button', { name: 'Continue automatic discussion', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Close panel', exact: true }).click()
    await page.locator('article').getByText('First, check the seal.', { exact: true }).waitFor()
    await expect.poll(() => preparation.textContent()).toContain('All ready · 2/2')
    expect(await page.locator('article').evaluate((element) => {
      const prep = element.querySelector('[data-discussion-id]')!
      const turn = [...element.querySelectorAll('section')].find(item => item.textContent?.includes('Let us examine the letter.'))!
      return Boolean(prep.compareDocumentPosition(turn) & Node.DOCUMENT_POSITION_FOLLOWING)
    })).toBe(true)
    await preparation.locator(':scope > details > summary').click()
    const preparedActors = preparation.getByRole('button', { name: /Ready$/u })
    await expect.poll(() => preparedActors.count()).toBe(2)
    await preparation.getByRole('button', { name: /UNREVEALED NAME/u }).click()
    await preparation.getByText('I should ask before opening the letter.', { exact: true }).waitFor()
    await preparation.scrollIntoViewIfNeeded()
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/discussion-preparation-expanded.png', import.meta.url)) })
    await preparation.locator(':scope > details > summary').click()
    await expect.poll(() => scaffold.ctx.roleplayPlay.read({ instanceId: instance.id, audience: { kind: 'observer' }, offset: 0, limit: 1 }).phase).toBe('ready')
    await page.getByRole('main').evaluate((element) => { element.scrollTop = 0 })
    const latest = page.getByRole('button', { name: 'Latest story', exact: true })
    await latest.waitFor()
    expect((await latest.boundingBox())?.width).toBeLessThanOrEqual(48)
    await latest.click()
    await expect.poll(() => page.getByRole('main').evaluate(element =>
      element.scrollHeight - element.scrollTop - element.clientHeight)).toBeLessThan(2)
    await page.getByRole('main').evaluate((element) => { element.scrollTop = 0 })
    const keeperTurn = page.locator('article > section').filter({ has: page.getByText('Let us examine the letter.', { exact: true }) })
    expect(await keeperTurn.locator('header strong').allTextContents()).toEqual(['UNREVEALED NAME'])
    await keeperTurn.getByRole('button', { name: 'Original context', exact: true }).click()
    const requestDialog = page.getByRole('dialog')
    await requestDialog.getByText('Recorded request input', { exact: true }).waitFor()
    await requestDialog.getByLabel('Search context', { exact: true }).fill('Quiet words')
    expect((await requestDialog.locator('pre').allTextContents()).join('\n')).toContain('Quiet words')
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/reading-context.png', import.meta.url)), fullPage: true })
    await page.keyboard.press('Escape')
    await keeperTurn.getByRole('button', { name: 'Thinking process', exact: true }).click()
    await expect.poll(() => keeperTurn.getByRole('button', { name: 'Thinking process', exact: true }).getAttribute('aria-expanded')).toBe('true')
    expect(await requestDialog.count()).toBe(0)
    await keeperTurn.getByRole('button', { name: 'Thinking process', exact: true }).click()
    await page.getByRole('textbox', { name: 'Player action or direction' }).fill('Preserve this draft.')
    await page.getByRole('button', { name: 'Background memory', exact: true }).click()
    const queueDialog = page.getByRole('dialog', { name: 'Background memory', exact: true })
    await queueDialog.getByText('No memory jobs yet.', { exact: false }).waitFor()
    await queueDialog.screenshot({ path: fileURLToPath(new URL('../../../.tmp/background-memory-panel.png', import.meta.url)) })
    await page.keyboard.press('Escape')
    expect(await page.getByRole('textbox', { name: 'Player action or direction' }).inputValue()).toBe('Preserve this draft.')
    await page.getByRole('button', { name: 'Memory review', exact: true }).click()
    const memoryDialog = page.getByRole('dialog', { name: 'Memory review', exact: true })
    await memoryDialog.getByLabel('Whose memory to review', { exact: true }).selectOption('keeper')
    await memoryDialog.getByText('I proposed examining the letter.', { exact: true }).waitFor()
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/ui-recovery-memory.png', import.meta.url)), fullPage: true })
    await page.keyboard.press('Escape')
    await memoryDialog.waitFor({ state: 'detached' })
    expect(await page.getByRole('textbox', { name: 'Player action or direction' }).inputValue()).toBe('Preserve this draft.')
    await page.getByRole('button', { name: 'Execution model', exact: true }).click()
    await page.getByRole('dialog', { name: 'Check execution model', exact: true }).waitFor()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Settings', exact: true }).click()
    await page.getByRole('button', { name: 'Increase font size', exact: true }).click()
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    const fontSize = await page.locator('body').evaluate(element => element.style.getPropertyValue('--dsh-content-font-size'))
    expect(await page.locator('article').evaluate(element => getComputedStyle(element).fontSize)).toBe(fontSize)
    expect(await page.getByRole('textbox', { name: 'Player action or direction' }).inputValue()).toBe('Preserve this draft.')
    await page.getByRole('textbox', { name: 'Player action or direction' }).fill('')
    await page.getByRole('main').evaluate((element) => { element.scrollTop = 0 })
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/independent-play.png', import.meta.url)), fullPage: true })
    await page.emulateMedia({ colorScheme: 'dark' })
    await expect.poll(() => page.locator('body').getAttribute('data-ds-dark-theme')).not.toBeNull()
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/player-ui-dark.png', import.meta.url)), fullPage: true })
    await page.emulateMedia({ colorScheme: 'light' })
    await page.getByRole('button', { name: 'Author workspace', exact: true }).click()
    await page.getByLabel('Characters', { exact: true }).selectOption('keeper')
    await page.getByRole('button', { name: 'Performance style', exact: true }).click()
    await page.getByLabel('Speech style', { exact: true }).fill('Changed after execution')
    await page.getByRole('button', { name: 'Save', exact: true }).first().click()
    await expect.poll(() => { const profile = scaffold.ctx.roleplayAuthor.workspace({ instanceId: instance.id, actorId: 'keeper' }).actor?.profile
      return profile?.kind === 'actor' ? profile.guidance.speechStyle : ''
    }).toBe('Changed after execution')
    await page.getByRole('button', { name: 'Context', exact: true }).click()
    const retention = page.getByRole('heading', { name: 'Memory review', exact: true }).locator('..')
    await retention.getByText('I proposed examining the letter.', { exact: true }).waitFor()
    await retention.getByText('Pending review', { exact: true }).waitFor()
    await retention.getByText('Source records', { exact: true }).click()
    const sourceId = scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper').retention.proposals[0]!.unit.sourceIds[0]!
    const sourceRecord = scaffold.ctx.roleplayRetentionViews.recall(instance.id, 'actor:keeper', { query: sourceId, offset: 0, limit: 20 })
    await retention.getByRole('button', { name: 'Read source 1', exact: true }).click()
    const sourceResults = retention.getByRole('region', { name: 'Source search results' })
    await expect.poll(() => sourceResults.textContent()).toContain(sourceRecord.entries[0]!.text)
    await sourceResults.getByText('Let us examine the letter.', { exact: true }).waitFor({ state: 'visible' })
    expect(await sourceResults.locator('pre').isVisible()).toBe(false)
    expect(scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper').retention.notes).toHaveLength(0)
    await retention.screenshot({ path: fileURLToPath(new URL('../../../.tmp/memory-source-review.png', import.meta.url)) })
    const activation = retention.getByRole('combobox', { name: 'Activation of new summaries', exact: true })
    await activation.selectOption('automatic')
    await expect.poll(() => scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper').retention.activation).toBe('automatic')
    await retention.getByText('Pending review', { exact: true }).waitFor()
    expect(scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper').retention.notes).toHaveLength(0)
    await retention.getByRole('button', { name: 'Approve', exact: true }).click()
    await retention.getByText('Approved', { exact: true }).waitFor()
    await retention.getByRole('button', { name: 'Correct memory', exact: true }).click()
    await retention.getByRole('textbox', { name: 'Brief understanding', exact: true }).fill('I proposed examining the letter; it remains unopened.')
    await retention.getByRole('textbox', { name: 'Character interpretation', exact: true }).fill('')
    await retention.getByRole('textbox', { name: 'Personal impact', exact: true }).fill('')
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/optional-memory-details.png', import.meta.url)), fullPage: true })
    await retention.getByRole('button', { name: 'Save', exact: true }).click()
    await retention.getByRole('textbox', { name: 'Brief understanding', exact: true }).waitFor({ state: 'detached' })
    await retention.getByText('I proposed examining the letter; it remains unopened.', { exact: true }).first().waitFor()
    await retention.getByText('Player correction.', { exact: true }).waitFor()
    await activation.selectOption('review')
    await expect.poll(() => scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper').retention.activation).toBe('review')
    await expect.poll(() => activation.inputValue()).toBe('review')
    await expect.poll(() => retention.getByRole('button', { name: 'Correct memory', exact: true }).isEnabled()).toBe(true)
    const corrected = scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper')
    expect(corrected.retention.notes[0]?.text).toBe('I proposed examining the letter; it remains unopened.')
    expect(corrected.retention.notes[0]?.episode).toEqual({ topic: 'The unopened letter', experience: 'I asked to examine the letter.', unresolved: [] })
    expect(corrected.retention.notes[0]?.status).toBe('active')
    await retention.screenshot({ path: fileURLToPath(new URL('../../../.tmp/player-ui-retention.png', import.meta.url)) })
    await retention.getByRole('button', { name: 'Disable summary and restore source context', exact: true }).click()
    await retention.getByRole('button', { name: 'Correct memory', exact: true }).waitFor({ state: 'detached' })
    expect(scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper').retention.notes[0]?.status).toBe('archived')
    expect(scaffold.ctx.roleplayRetentionViews.review(instance.id, 'actor:keeper', corrected.revision).retention.notes[0]?.status).toBe('active')
    const originals = scaffold.ctx.roleplayRetentionViews.recall(instance.id, 'actor:keeper',
      { query: corrected.retention.notes[0]!.sourceIds[0]!, offset: 0, limit: 20 })
    expect(JSON.stringify(originals)).toContain('Let us examine the letter.')
    const requests = page.getByRole('heading', { name: 'Actual model requests', exact: true }).locator('..')
    await requests.getByRole('button', { name: 'Refresh', exact: true }).click()
    await requests.getByRole('button', { name: /^Turn \d+ · request \d+$/u }).first().click()
    await requests.getByText('Recorded request input', { exact: true }).waitFor()
    await requests.getByRole('tab', { name: 'Raw JSON', exact: true }).click()
    const requestBody = requests.getByText('Recorded request input', { exact: true }).locator('..').locator('pre')
    expect((await requestBody.innerText()).length).toBeGreaterThan(100)
    expect(await requestBody.innerText()).toContain('Quiet words')
    expect(await requestBody.innerText()).not.toContain('Changed after execution')
    await requests.getByRole('tab', { name: 'Response and tools', exact: true }).click()
    await requests.getByRole('heading', { name: 'Recorded model response', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Storybooks', exact: true }).last().click()
    await page.getByRole('button', { name: 'Independent Ledger', exact: true }).last().click()
    await page.getByRole('button', { name: 'Characters', exact: true }).click()
    const protagonist = page.getByRole('combobox', { name: 'Narrative protagonist', exact: true })
    expect(await protagonist.inputValue()).toBe('')
    await protagonist.selectOption('keeper')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayBooks.draft(draft.id)?.document.protagonistActorId).toBe('keeper')
    await expect.poll(() => page.getByRole('button', { name: 'Save', exact: true }).isEnabled()).toBe(true)
    await protagonist.selectOption('')
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayBooks.draft(draft.id)?.document.protagonistActorId).toBeNull()
    await page.getByRole('button', { name: 'Review publication', exact: true }).click()
    await page.getByRole('button', { name: 'Publish reviewed version', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayBooks.draft(draft.id)?.latestVersionId).not.toBe(version.id)
    expect(scaffold.ctx.roleplayHistory.snapshot(instance.id).instance.templateVersionId).toBe(version.id)
    await page.getByRole('button', { name: 'History and recovery', exact: true }).click()
    const boundary = scaffold.ctx.roleplayHistory.snapshot(instance.id)
    await page.getByLabel('Checkpoint name', { exact: true }).fill('Before the storm')
    await page.getByRole('button', { name: 'Save checkpoint', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayHistory.checkpoints(instance.id).length).toBe(1)
    await page.getByRole('main').getByRole('button', { name: 'Refresh', exact: true }).click()
    await page.getByRole('button', { name: 'Before the storm', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    await page.getByRole('button', { name: 'World intervention', exact: true }).click()
    await page.getByRole('textbox', { name: 'Player action or direction' }).fill('Lightning splits the courtyard tree.')
    await page.getByRole('button', { name: 'Submit', exact: true }).click()
    await page.locator('article').getByText('Lightning splits the courtyard tree.', { exact: true }).waitFor()
    const changedRevision = scaffold.ctx.roleplayHistory.snapshot(instance.id).instance.revision
    await page.getByRole('button', { name: 'History and recovery', exact: true }).click()
    await page.getByRole('button', { name: 'Restore this boundary, retaining history', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayHistory.snapshot(instance.id).instance.revision).toBe(changedRevision + 1)
    expect(scaffold.ctx.roleplayHistory.snapshot(instance.id).entities).toEqual(boundary.entities)
    const changedView = scaffold.ctx.roleplayPlay.read({ instanceId: instance.id, audience: { kind: 'observer' }, revision: changedRevision, offset: 0, limit: 40 })
    expect(changedView.rows.some(row => row.text === 'Lightning splits the courtyard tree.')).toBe(true)
    await page.getByRole('button', { name: 'Before the storm', exact: true }).click()
    await page.getByRole('button', { name: 'Return to current story', exact: true }).click()
    const downloadEvent = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Export independent story', exact: true }).click()
    const download = await downloadEvent
    const downloadPath = join(root, 'exported-story.json')
    await download.saveAs(downloadPath)
    const exported = JSON.parse(await readFile(downloadPath, 'utf8')) as { executionEvidence: unknown[] }
    expect(exported.executionEvidence.length).toBeGreaterThan(0)
    await page.getByRole('button', { name: 'Storybooks', exact: true }).last().click()
    await page.getByRole('button', { name: 'Import your work', exact: true }).last().click()
    await page.getByRole('button', { name: 'Import independent archive', exact: true }).first().click()
    await page.getByLabel('Import independent archive', { exact: true }).setInputFiles(downloadPath)
    await page.getByRole('button', { name: 'Import independent archive', exact: true }).last().click()
    await expect.poll(() => scaffold.ctx.roleplayAuthor.instances().length).toBe(2)
    const imported = scaffold.ctx.roleplayAuthor.instances().find(item => item.id !== instance.id)!
    expect(scaffold.ctx.roleplayHistory.snapshot(imported.id).instance.templateVersionId).not.toBe(version.id)
    expect(scaffold.ctx.roleplayViews.authorCognition(imported.id, 'keeper').current.dynamicState.entries)
      .toEqual(scaffold.ctx.roleplayViews.authorCognition(instance.id, 'keeper').current.dynamicState.entries)
    await page.locator('article').getByText('The shutters rattle in the wind.', { exact: true }).waitFor()
    expect(Math.round((await page.locator('article').boundingBox())!.width)).toBe(840)
    await expect.poll(() => page.getByRole('main').textContent()).toContain('UNREVEALED NAME')
    await page.getByRole('button', { name: 'Author workspace', exact: true }).click()
    await page.getByLabel('Characters', { exact: true }).selectOption('keeper')
    await page.getByRole('button', { name: 'Context', exact: true }).click()
    const importedRequests = page.getByRole('heading', { name: 'Actual model requests', exact: true }).locator('..')
    await importedRequests.getByRole('button', { name: 'Refresh', exact: true }).click()
    await importedRequests.getByText('Execution evidence from imported archive', { exact: true }).first().waitFor()
    await importedRequests.getByRole('button', { name: /^Turn \d+ · request \d+$/u }).first().click()
    await importedRequests.getByText('Recorded request input', { exact: true }).waitFor()
    await importedRequests.getByRole('tab', { name: 'Raw JSON', exact: true }).click()
    const importedBody = importedRequests.getByText('Recorded request input', { exact: true }).locator('..').locator('pre')
    expect(await importedBody.innerText()).toContain('Quiet words')
    expect(await importedBody.innerText()).not.toContain('Changed after execution')
    await importedRequests.getByRole('tab', { name: 'Response and tools', exact: true }).click()
    await importedRequests.getByRole('heading', { name: 'Recorded model response', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Characters', exact: true }).click()
    await page.getByRole('heading', { name: 'Collect into a book draft', exact: true }).waitFor()
    await page.getByText('Select people and preview material', { exact: true }).click()
    const extraction = page.locator('summary').filter({ hasText: 'Select people and preview material' }).locator('..')
    await extraction.getByLabel('Title', { exact: true }).fill('Selected innkeeper material')
    await extraction.getByLabel('UNREVEALED NAME', { exact: true }).check()
    await extraction.getByRole('button', { name: 'Review publication', exact: true }).click()
    await extraction.locator('pre').waitFor()
    const selectedDocument = JSON.parse(await extraction.locator('pre').innerText()) as { characters: { displayName: string }[] }
    expect(selectedDocument.characters).toHaveLength(1)
    expect(selectedDocument.characters[0]?.displayName).toBe('UNREVEALED NAME')
    expect(JSON.stringify(selectedDocument)).not.toContain('Unease')
    expect(JSON.stringify(selectedDocument)).not.toContain('New messenger')
    await extraction.getByRole('button', { name: 'Collect into a book draft', exact: true }).click()
    await page.getByRole('button', { name: 'Selected innkeeper material', exact: true }).last().waitFor()
    expect(scaffold.ctx.roleplayHistory.snapshot(imported.id).instance.templateVersionId).toBe(imported.templateVersionId)
    await page.getByRole('button', { name: 'Author workspace', exact: true }).click()
    await page.getByLabel('Characters', { exact: true }).selectOption('keeper')
    await page.getByRole('button', { name: 'Context', exact: true }).click()
    await page.getByRole('button', { name: 'Story settings', exact: true }).click()
    await page.getByText('Execution model (all stories)', { exact: true }).click()
    await page.getByLabel('Model ID', { exact: true }).fill('mock-next')
    await page.getByRole('button', { name: 'Save execution model', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayExecutionModel.read().selection.model).toBe('mock-next')
    // The native composer selector writes the story execution route, independently of chat sessions.
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    await page.getByRole('button', { name: /Select model, current Mock Next/ }).click()
    await page.getByRole('menuitem', { name: /^Model/ }).click()
    await page.getByRole('menuitemradio', { name: 'Mock', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayExecutionModel.read().selection.model).toBe('mock')
    await page.getByRole('button', { name: 'Select model, current Mock', exact: true }).click()
    await page.getByRole('menuitem', { name: /^Model/ }).click()
    await page.getByRole('menuitemradio', { name: 'Mock Next', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayExecutionModel.read().selection.model).toBe('mock-next')
    await page.getByRole('button', { name: /Select model, current Mock Next/ }).click()
    await page.getByRole('menuitem', { name: /^Effort/ }).click()
    await page.getByRole('menuitemradio', { name: 'High', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayExecutionModel.read().selection.reasoningEffort).toBe('high')
    await page.getByRole('button', { name: /Select model, current Mock Next, reasoning effort High/ }).waitFor()
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/composer-native-model.png', import.meta.url)), fullPage: true })
    await page.getByRole('button', { name: 'Author workspace', exact: true }).click()
    await page.getByLabel('Characters', { exact: true }).selectOption('keeper')
    const modelRevision = scaffold.ctx.roleplayExecutionModel.read().revision
    await expect(scaffold.ctx.roleplayExecutionModel.save({ expectedRevision: modelRevision - 1,
      selection: { provider: 'mock', model: 'stale-model' } })).rejects.toThrow()
    expect(scaffold.ctx.roleplayExecutionModel.read().selection.model).toBe('mock-next')
    await page.getByRole('button', { name: 'Context', exact: true }).click()
    const live = page.getByRole('heading', { name: 'Live execution diagnostics', exact: true }).locator('..')
    await live.getByLabel('Watch live model drafts for this perspective (author access)', { exact: true }).check()
    const liveRun = scaffold.ctx.roleplayRuntime.run({ instanceId: imported.id, id: 'browser-live' as CommandId,
      expectedRevision: scaffold.ctx.roleplayHistory.snapshot(imported.id).instance.revision, principal: { kind: 'player' } }, 'keeper')
      .then(() => null, (error: unknown) => error)
    await live.getByText('A private diagnostic draft.', { exact: true }).waitFor()
    expect(await live.innerText()).toContain('mock-next')
    expect(storyAdapter.requests.at(-1)?.model).toBe('mock-next')
    expect(storyAdapter.requests.at(-1)?.reasoningEffort).toBe('high')
    await live.getByText('Partial response recorded; no finish recorded', { exact: true }).waitFor()
    expect(scaffold.ctx.roleplayPlay.read({ instanceId: imported.id, audience: { kind: 'observer' }, offset: 0, limit: 40 }).rows)
      .not.toEqual(expect.arrayContaining([expect.objectContaining({ text: 'A private diagnostic draft.' })]))
    const messenger = scaffold.ctx.roleplayViews.authorPeople(imported.id, { query: 'New messenger', offset: 0, limit: 20 }).entries[0]!
    await page.getByLabel('Characters', { exact: true }).selectOption(messenger.definition.actorId)
    await expect.poll(async () => page.getByText('A private diagnostic draft.', { exact: true }).count()).toBe(0)
    scaffold.ctx.roleplayRuntime.cancel({ instanceId: imported.id, id: 'cancel-browser-live' as CommandId,
      expectedRevision: scaffold.ctx.roleplayHistory.snapshot(imported.id).instance.revision, principal: { kind: 'player' } }, 'Browser diagnostic complete')
    expect(String(await liveRun)).toContain('Browser diagnostic complete')
    await page.reload({ waitUntil: 'load' })
    await page.getByRole('button', { name: 'Play', exact: true }).click()
    await page.getByRole('textbox', { name: 'Player action or direction' }).waitFor()
    await expect.poll(async () => page.getByRole('button', { name: /Story run \d+ Pinned version 1/u }).count()).toBe(2)
    await page.getByRole('button', { name: /Story run \d+ Pinned version 1/u }).last().click()
    await page.setViewportSize({ width: 390, height: 844 })
    await expect.poll(async () => (await page.getByRole('main').boundingBox())?.width ?? 0).toBeGreaterThan(300)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect((await page.getByRole('textbox', { name: 'Player action or direction' }).boundingBox())?.width).toBeGreaterThan(200)
    await page.screenshot({ path: fileURLToPath(new URL('../../../.tmp/independent-narrow.png', import.meta.url)), fullPage: true })
    await page.setViewportSize({ width: 1280, height: 900 })
    await page.getByRole('button', { name: 'Storybooks', exact: true }).last().click()
    await page.getByRole('button', { name: 'Import your work', exact: true }).last().click()
    await page.getByLabel('Import storybook JSON', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{') })
    await page.getByRole('alert').filter({ hasText: 'Cannot parse JSON' }).waitFor()
    expect(await page.getByRole('button', { name: 'Validate and import draft', exact: true }).isDisabled()).toBe(true)
    await page.getByLabel('Import storybook JSON', { exact: true }).setInputFiles(fileURLToPath(new URL(
      '../../../packages/experimental/roleplay-web-profile/tests/fixtures/storybooks/moonshadow-ledger/storybook.json', import.meta.url)))
    await page.getByRole('button', { name: 'Validate and import draft', exact: true }).click()
    await page.getByRole('button', { name: 'Review publication', exact: true }).click()
    await page.getByRole('button', { name: 'Publish reviewed version', exact: true }).click()
    const moon = page.getByRole('button', { name: '月影账簿', exact: true }).last().locator('..')
    await moon.getByRole('button', { name: 'New story instance', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayBooks.instances().length).toBe(3)
    await page.getByRole('button', { name: '月影账簿', exact: true }).first().click()
    const bookDownloadEvent = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Export storybook', exact: true }).click()
    const bookDownload = await bookDownloadEvent
    expect(bookDownload.suggestedFilename()).toBe('月影账簿.storybook.json')
    const bookPath = join(root, 'exported-book.json')
    await bookDownload.saveAs(bookPath)
    const exportedBook = JSON.parse(await readFile(bookPath, 'utf8')) as { format: string; document: { characters: unknown[] }; resources: unknown[] }
    expect(exportedBook.format).toBe('storyweaver-book')
    const countBeforeImport = scaffold.ctx.roleplayBooks.list().length
    await page.getByRole('button', { name: 'Import your work', exact: true }).last().click()
    await page.getByLabel('Import storybook JSON', { exact: true }).setInputFiles(bookPath)
    await page.getByRole('button', { name: 'Validate and import draft', exact: true }).click()
    await expect.poll(() => scaffold.ctx.roleplayBooks.list().length).toBe(countBeforeImport + 1)
    expect(scaffold.ctx.roleplayBooks.instances()).toHaveLength(3)
    expect(scaffold.ctx.get('storyRegistry')).toBeUndefined()
    expect(scaffold.ctx.get('actor')).toBeUndefined()
    expect(console.pageErrors).toEqual([])
  } catch (error) {
    const page = browser.contexts()[0]?.pages()[0]
    throw new Error(`${String(error)}\n${page === undefined ? 'Browser page closed' : await page.locator('body').innerText()}`, { cause: error })
  } finally { await browser.close(); await scaffold.close(); await rm(root, { recursive: true, force: true }) }
}, 120000)
